#!/bin/sh
# >>> sediment-attribution >>>
(
    __sediment_status=$?
    python3 "/opt/sediment/sediment_attribution.py" stamp || true
    exit "$__sediment_status"
) && :
# <<< sediment-attribution <<<
