# SPDX-License-Identifier: AGPL-3.0-or-later
"""Sediment export: thin, stateless projections over the canonical derived
artifacts (ADR 0004) and their local destinations.

Attributed completions (``attributed_completions.py``) are the first canonical
artifact; the RLVR artifacts (``tasks.jsonl``, ``rollouts.jsonl``) project
over rollouts, the second, with an optional taskset-level
``environment.yaml`` sidecar (``environment_manifest.py``). DPO (``dpo.py``)
and SFT (``sft.py``) project over attributed completions, sharing the baseline
label-confidence policy (``label_confidence.py``). Diff-shaped SFT (``diff_sft.py``)
reshapes the same attributed completions and policy into per-commit, per-file
training rows; recovery (``recovery.py``) projects the one fact-derived
training-row format (ADR 0004) into rows, stamping the eval split
at projection time since ``RecoverySample`` carries none.

The per-model outcome report (``outcome_report.py``) aggregates over attributed
completions, and its stdlib-only two-proportion significance testing
(``significance.py``) compares two such rows. Label-confidence inspection
(``label_confidence_inspection.py``) stratify-samples attributed completions across the
confidence ladder's real branches and surfaces ``resolve_confidence``'s
factor breakdown per row, for ``sediment report label-confidence-inspection``.
Inter-rater reliability (``interrater.py``) computes standalone Cohen's kappa
over future multi-labeler review columns; label-confidence sensitivity
(``label_confidence_sensitivity.py``) sweeps one ``LabelConfidencePolicy`` knob at a time over a
fixed attributed-completion set; decision-latency diagnostics
(``decision_latency.py``) bucket those same joined decisions by
inference-call-to-decision latency.

All export formats stay open-core (ADR 0006)."""

from .calibration import (
    BucketInversion,
    CalibrationPair,
    CalibrationRecord,
    CalibrationMetrics,
    CalibrationPolicyComparison,
    CalibrationStratum,
    ReliabilityBucket,
    auroc,
    brier_score,
    bucket_inversions,
    compare_calibration_policies,
    expected_calibration_error,
    reliability_diagram_data,
    stratify_calibration,
)
from .accepted_work_lifecycle import (
    AcceptedWorkLifecycleReport,
    AcceptedWorkProgression,
    EditRetentionPanel,
    LifecycleCoverage,
    LifecycleProvenance,
    LifecycleReportPolicy,
    LifecycleStage,
    LifecycleStratum,
    MergeDurabilityPanel,
    ReworkComponent,
    SessionAttritionPanel,
    SessionExamples,
    generate_accepted_work_lifecycle_report,
)
from .config import LabelConfidenceSettings
from .dataset_diagnostics import (
    DPOBucketSparsityReport,
    ConfidenceDistributionRow,
    ConfidenceFloorExclusionRow,
    CrossSplitDuplicateExample,
    CrossSplitDuplicateReport,
    DEFAULT_DPO_NEAR_DUPLICATE_THRESHOLD,
    DPONearDuplicateBucketExample,
    DPONearDuplicateBucketReport,
    DatasetDiagnostics,
    DistributionStats,
    FateDiagnostic,
    ModelBalanceRow,
    build_dataset_diagnostics,
    build_dpo_bucket_sparsity,
    generate_dataset_diagnostics,
)
from .decision_latency import (
    DecisionLatencyBucket,
    DecisionLatencyReport,
    build_decision_latency_report,
    generate_decision_latency_report,
)
from .derived_bundle import (
    BundleFileMetadata,
    BundleManifest,
    BundleRecord,
    BundleValidationError,
    DerivedBundle,
    DerivationPolicy,
    DerivationScope,
    build_derived_bundle,
    build_derived_bundle_context,
    load_derivation_policy,
    read_derived_bundle,
    open_derived_bundle,
    BundleLimits,
    BundleCapacityError,
    BundleRecordStore,
    validate_derived_bundle,
    write_derived_bundle,
)
from .diff_sft import DiffSFTMetadata, DiffSFTSample, SourceIds, project_diff_sft
from .diff_sft import DIFF_SFT_SKIP_REASONS, DiffSFTSkipReason
from .diff_sft import Projection as DiffSFTProjection
from .diff_sft import to_export_rows as diff_sft_to_export_rows
from .dpo import (
    DPO_RECIPE_VERSION,
    DPO_SKIP_REASONS,
    DPOChosenLabelSource as DPOChosenLabelSource,
    DPOLabelSource,
    DPOMetadata,
    DPOPair,
    DPOPolicy,
    DPOProvenance,
    DPORecipeId,
    DPORecipeVersion,
    DPORejectedLabelSource as DPORejectedLabelSource,
    DPOSkipReason,
    project_dpo,
)
from .dpo import Projection as DPOProjection
from .dpo import to_export_rows as dpo_to_export_rows
from .environment_manifest import (
    NemoGymRuntimeSettings,
    OpenEnvRuntimeSettings,
    build_manifest,
    write_manifest,
)
from .interrater import (
    InterRaterAgreement,
    Label,
    cohens_kappa,
    percent_agreement,
)
from .jsonl import ExportRow, WriteResult, write_jsonl
from .outcome_report import (
    CIGrain,
    MantelHaenszelRiskDifference,
    DiffSizeStats,
    MannKendallTrendTest,
    ModelOutcomeReport,
    ModelOutcomeReportResult,
    RepositoryShrunkRates,
    ModelTemporalTrend,
    OutcomeReportPolicy,
    RecoveryDiffSizeDistribution,
    RecoveryYieldReport,
    SignalFunnelReport,
    StratificationCheck,
    StratificationComparison,
    StratificationMetric,
    StratificationReversal,
    StratificationStatus,
    StratifiedRate,
    TemporalTrendWindow,
    TrendMetric,
    TrendStatus,
    ShrunkStratifiedRate,
    build_model_report,
    build_model_report_result,
    build_recovery_yield_report,
    build_signal_funnel_report,
    build_stratification_checks,
    build_temporal_trend_report,
    derive_model_report_attribution_share,
    generate_model_report,
    generate_model_report_result,
    generate_recovery_yield_report,
    mann_kendall_trend_test,
    shrink_stratified_rates,
    scope_model_report_evidence,
    wilson_score_interval,
)
from .operational_scope import OperationalReportScope
from .price_manifest import ModelPrice as ModelPrice
from .price_manifest import PriceManifest as PriceManifest
from .recovery import (
    RECOVERY_PROJECTION_SKIP_REASONS as RECOVERY_PROJECTION_SKIP_REASONS,
    RECOVERY_RECIPE_ID,
    RECOVERY_RECIPE_VERSION,
    RecoveryProjectionSkipReason as RecoveryProjectionSkipReason,
    RecoveryRow,
    RecoveryRecipeId,
    RecoveryRecipeVersion,
    project_recovery,
)
from .recovery import Projection as RecoveryProjection
from .recovery import to_export_rows as recovery_to_export_rows
from .label_confidence import (
    ConfidenceBreakdown,
    DecisionBranch,
    LabelConfidencePolicy,
    ci_failed,
    ci_passed,
    decision_branch,
    resolve_confidence,
    resolve_confidence_breakdown,
    resolve_ci_resolution,
    resolve_ci_resolution_result,
    resolve_policy_v3_confidence,
)
from .verifier_commands import VerifierCommands, VerifierCommandsSettings
from .label_confidence_inspection import (
    CIOutcomeSummary,
    DecisionSummary,
    InspectionRow,
    build_label_confidence_inspection,
    generate_label_confidence_inspection,
    stratified_sample,
)
from .label_confidence_sensitivity import (
    DEFAULT_SWEEP_GRIDS,
    LABEL_CONFIDENCE_POLICY_KNOBS,
    ConfidenceStats,
    LabelConfidencePolicyKnob,
    LabelConfidenceSensitivityRow,
    build_label_confidence_sensitivity,
    generate_label_confidence_sensitivity,
)
from .rlvr import (
    NemoGymMetadata,
    NemoGymResponse,
    NemoGymResponsesCreateParams,
    NemoGymRolloutRow,
    Projection,
    RLVRDecisionRow,
    RLVRInferenceMessageRow,
    RLVREcipeId,
    RLVRRecipeVersion,
    RLVRRewardSource,
    RLVRTarget,
    RLVRTurnRow,
    SWEBenchMetadata,
    SWEBenchTaskRow,
    SedimentRolloutRow,
    SedimentTaskRow,
    Verification,
    export_rlvr,
    export_rlvr_from_rollouts,
    export_rlvr_from_bundle,
    project_nemo_gym_rollouts,
    project_sediment_rollouts,
    project_sediment_tasks,
    project_swe_bench_tasks,
)
from .sft import Projection as SFTProjection
from .sft import (
    SFT_CURATED_V1_STRONG_RETENTION_THRESHOLD,
    SFT_RECIPE_VERSION,
    SFT_SKIP_REASONS,
    SFTEligibilitySource,
    SFTMetadata,
    SFTPolicy,
    SFTRecipeId,
    SFTRecipeVersion,
    SFTSkipReason,
    SFTSample,
    project_sft,
)
from .sft import to_export_rows as sft_to_export_rows
from .significance import (
    DEFAULT_BOOTSTRAP_ITERATIONS,
    DEFAULT_BOOTSTRAP_SEED,
    BayesianProportionComparison,
    BootstrapIntervalDiagnostic,
    EffectDecayCheckpoint,
    EffectDecayReport,
    ModelComparison,
    MultiModelComparison,
    NonInferiorityResult,
    PowerSimulationResult,
    ProportionComparison,
    RegretAlternative,
    RegretReport,
    SequentialBoundary,
    beta_binomial_probability_of_improvement,
    bootstrap_two_proportion_interval_diagnostic,
    cohens_h,
    compare_all_models,
    compare_models,
    effect_decay_check,
    expected_regret,
    minimum_detectable_effect,
    non_inferiority_test,
    obrien_fleming_alpha_spent,
    obrien_fleming_boundary,
    required_days_for_mde,
    required_n_per_arm_for_mde,
    simulate_two_proportion_power,
    two_proportion_z_test,
)
from .attributed_completions import (
    AbandonmentSummary,
    AttributedCompletion,
    AttributedCompletionAssemblyResult,
    AttributedCompletionPolicy,
    AttributedCompletionResult,
    assemble_attributed_completion_result,
    assemble_attributed_completions,
    assemble_attributed_completions_result,
    build_abandonment_summary,
)
from .merge_retention_report import (
    RETENTION_THRESHOLDS,
    MergeRetentionReport,
    MergeRetentionReportResult,
    RetentionDistribution,
    RetentionScoreSummary,
    RetentionThreshold,
    build_merge_retention_report,
    generate_merge_retention_report,
    generate_merge_retention_report_result,
    merge_retention_to_export_rows,
)

__all__ = [
    "AcceptedWorkLifecycleReport",
    "AcceptedWorkProgression",
    "EditRetentionPanel",
    "LifecycleCoverage",
    "LifecycleProvenance",
    "LifecycleReportPolicy",
    "LifecycleStage",
    "LifecycleStratum",
    "MergeDurabilityPanel",
    "ReworkComponent",
    "SessionAttritionPanel",
    "SessionExamples",
    "generate_accepted_work_lifecycle_report",
    "AbandonmentSummary",
    "CIGrain",
    "CIOutcomeSummary",
    "ConfidenceBreakdown",
    "ConfidenceStats",
    "DPOPair",
    "DPOMetadata",
    "DPOPolicy",
    "DPOProvenance",
    "DPOProjection",
    "DPORecipeId",
    "DPORecipeVersion",
    "DPOLabelSource",
    "DPOSkipReason",
    "DPO_RECIPE_VERSION",
    "DPO_SKIP_REASONS",
    "DEFAULT_DPO_NEAR_DUPLICATE_THRESHOLD",
    "DPONearDuplicateBucketExample",
    "DPONearDuplicateBucketReport",
    "DPOBucketSparsityReport",
    "ConfidenceDistributionRow",
    "ConfidenceFloorExclusionRow",
    "CrossSplitDuplicateExample",
    "CrossSplitDuplicateReport",
    "DatasetDiagnostics",
    "DEFAULT_SWEEP_GRIDS",
    "DecisionBranch",
    "DecisionLatencyBucket",
    "DecisionLatencyReport",
    "DerivationPolicy",
    "DerivationScope",
    "DerivedBundle",
    "DecisionSummary",
    "DiffSFTProjection",
    "DiffSFTSample",
    "DiffSizeStats",
    "DistributionStats",
    "FateDiagnostic",
    "derive_model_report_attribution_share",
    "ExportRow",
    "EffectDecayCheckpoint",
    "EffectDecayReport",
    "DiffSFTMetadata",
    "DiffSFTSkipReason",
    "DIFF_SFT_SKIP_REASONS",
    "BucketInversion",
    "BundleValidationError",
    "BundleFileMetadata",
    "BundleManifest",
    "BundleRecord",
    "BootstrapIntervalDiagnostic",
    "CalibrationPair",
    "CalibrationRecord",
    "CalibrationMetrics",
    "CalibrationPolicyComparison",
    "CalibrationStratum",
    "InspectionRow",
    "MantelHaenszelRiskDifference",
    "InterRaterAgreement",
    "Label",
    "MannKendallTrendTest",
    "ModelComparison",
    "MultiModelComparison",
    "ModelOutcomeReport",
    "ModelOutcomeReportResult",
    "RepositoryShrunkRates",
    "ModelTemporalTrend",
    "ModelBalanceRow",
    "NonInferiorityResult",
    "NemoGymRuntimeSettings",
    "OpenEnvRuntimeSettings",
    "OutcomeReportPolicy",
    "OperationalReportScope",
    "PowerSimulationResult",
    "Projection",
    "ProportionComparison",
    "RegretAlternative",
    "RegretReport",
    "VerifierCommands",
    "VerifierCommandsSettings",
    "LabelConfidencePolicy",
    "LabelConfidencePolicyKnob",
    "LabelConfidenceSettings",
    "LabelConfidenceSensitivityRow",
    "RecoveryYieldReport",
    "RecoveryDiffSizeDistribution",
    "RecoveryProjection",
    "RecoveryRow",
    "RecoveryRecipeId",
    "RecoveryRecipeVersion",
    "RECOVERY_RECIPE_ID",
    "RECOVERY_RECIPE_VERSION",
    "RLVREcipeId",
    "RLVRRecipeVersion",
    "RLVRRewardSource",
    "RLVRTarget",
    "RLVRDecisionRow",
    "RLVRInferenceMessageRow",
    "RLVRTurnRow",
    "ReliabilityBucket",
    "SequentialBoundary",
    "SFTPolicy",
    "SFTRecipeId",
    "SFTRecipeVersion",
    "SFTEligibilitySource",
    "SFTSkipReason",
    "SFT_RECIPE_VERSION",
    "SFT_SKIP_REASONS",
    "SFT_CURATED_V1_STRONG_RETENTION_THRESHOLD",
    "SFTMetadata",
    "SFTProjection",
    "SFTSample",
    "SWEBenchMetadata",
    "SWEBenchTaskRow",
    "SedimentRolloutRow",
    "SedimentTaskRow",
    "SignalFunnelReport",
    "SourceIds",
    "StratificationCheck",
    "StratificationComparison",
    "StratificationMetric",
    "StratificationReversal",
    "StratificationStatus",
    "StratifiedRate",
    "TemporalTrendWindow",
    "TrendMetric",
    "TrendStatus",
    "ShrunkStratifiedRate",
    "AttributedCompletion",
    "AttributedCompletionAssemblyResult",
    "AttributedCompletionPolicy",
    "AttributedCompletionResult",
    "MergeRetentionReport",
    "MergeRetentionReportResult",
    "RetentionDistribution",
    "RetentionScoreSummary",
    "RetentionThreshold",
    "RETENTION_THRESHOLDS",
    "WriteResult",
    "assemble_attributed_completions",
    "assemble_attributed_completion_result",
    "assemble_attributed_completions_result",
    "BayesianProportionComparison",
    "beta_binomial_probability_of_improvement",
    "auroc",
    "build_dataset_diagnostics",
    "build_abandonment_summary",
    "build_derived_bundle",
    "build_derived_bundle_context",
    "build_dpo_bucket_sparsity",
    "build_decision_latency_report",
    "build_manifest",
    "build_merge_retention_report",
    "brier_score",
    "bucket_inversions",
    "build_model_report",
    "build_model_report_result",
    "build_recovery_yield_report",
    "build_label_confidence_inspection",
    "build_signal_funnel_report",
    "build_label_confidence_sensitivity",
    "build_stratification_checks",
    "bootstrap_two_proportion_interval_diagnostic",
    "build_temporal_trend_report",
    "ci_failed",
    "ci_passed",
    "cohens_h",
    "cohens_kappa",
    "compare_all_models",
    "compare_calibration_policies",
    "compare_models",
    "decision_branch",
    "DEFAULT_BOOTSTRAP_ITERATIONS",
    "DEFAULT_BOOTSTRAP_SEED",
    "diff_sft_to_export_rows",
    "dpo_to_export_rows",
    "effect_decay_check",
    "export_rlvr",
    "export_rlvr_from_rollouts",
    "export_rlvr_from_bundle",
    "expected_regret",
    "expected_calibration_error",
    "generate_decision_latency_report",
    "generate_model_report",
    "generate_merge_retention_report",
    "generate_dataset_diagnostics",
    "generate_model_report_result",
    "generate_recovery_yield_report",
    "generate_label_confidence_inspection",
    "mann_kendall_trend_test",
    "load_derivation_policy",
    "read_derived_bundle",
    "open_derived_bundle",
    "BundleLimits",
    "BundleCapacityError",
    "BundleRecordStore",
    "validate_derived_bundle",
    "generate_label_confidence_sensitivity",
    "minimum_detectable_effect",
    "percent_agreement",
    "non_inferiority_test",
    "obrien_fleming_alpha_spent",
    "obrien_fleming_boundary",
    "project_diff_sft",
    "project_dpo",
    "project_nemo_gym_rollouts",
    "project_recovery",
    "project_sediment_rollouts",
    "project_sediment_tasks",
    "project_sft",
    "project_swe_bench_tasks",
    "LABEL_CONFIDENCE_POLICY_KNOBS",
    "recovery_to_export_rows",
    "reliability_diagram_data",
    "required_days_for_mde",
    "required_n_per_arm_for_mde",
    "resolve_confidence",
    "resolve_confidence_breakdown",
    "resolve_ci_resolution",
    "resolve_ci_resolution_result",
    "resolve_policy_v3_confidence",
    "sft_to_export_rows",
    "simulate_two_proportion_power",
    "shrink_stratified_rates",
    "scope_model_report_evidence",
    "stratified_sample",
    "stratify_calibration",
    "two_proportion_z_test",
    "write_jsonl",
    "generate_merge_retention_report_result",
    "merge_retention_to_export_rows",
    "write_derived_bundle",
    "write_manifest",
    "wilson_score_interval",
    "NemoGymMetadata",
    "NemoGymResponse",
    "NemoGymResponsesCreateParams",
    "NemoGymRolloutRow",
    "Verification",
]
