# SPDX-License-Identifier: AGPL-3.0-or-later
"""Create the frozen PostgreSQL fact-store baseline.

Revision ID: 0001_postgresql_baseline
Revises:
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = "0001_postgresql_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ci_outcomes",
        sa.Column("schema_version", sa.BigInteger(), nullable=False),
        sa.Column("outcome_id", sa.Text(), nullable=False),
        sa.Column("org_id", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("run_attempt", sa.BigInteger(), nullable=True),
        sa.Column("repo", sa.Text(), nullable=False),
        sa.Column("commit_sha", sa.Text(), nullable=False),
        sa.Column("branch", sa.Text(), nullable=False),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("workflow_name", sa.Text(), nullable=False),
        sa.Column("workflow_id", sa.Text(), nullable=True),
        sa.Column("workflow_path", sa.Text(), nullable=True),
        sa.Column("run_url", sa.Text(), nullable=True),
        sa.Column("provider_result", sa.Text(), nullable=True),
        sa.Column("error_type", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("source_event_type", sa.Text(), nullable=True),
        sa.Column("source_spec_version", sa.Text(), nullable=True),
        sa.Column("source_event_id", sa.Text(), nullable=True),
        sa.Column("pr_number", sa.BigInteger(), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "branch NOT LIKE 'refs/heads/%' AND branch = btrim(branch, E' \\t\\n\\r')",
            name="ck_ci_outcomes_branch",
        ),
        sa.CheckConstraint(
            "commit_sha ~ '^(?:[0-9a-f]{40}|[0-9a-f]{64})$'",
            name="ck_ci_outcomes_commit_sha",
        ),
        sa.CheckConstraint(
            "error_type IS NULL OR (error_type <> '' AND error_type = btrim(error_type, E' \\t\\n\\r'))",
            name="ck_ci_outcomes_error_type",
        ),
        sa.CheckConstraint(
            "org_id ~ '^[a-z0-9][a-z0-9._-]{0,63}$'", name="ck_ci_outcomes_org_id"
        ),
        sa.CheckConstraint(
            "outcome_id <> '' AND outcome_id = btrim(outcome_id, E' \\t\\n\\r')",
            name="ck_ci_outcomes_outcome_id",
        ),
        sa.CheckConstraint(
            "provider IN ('github_actions', 'jenkins', 'gitlab_ci', 'circleci', 'buildkite', 'other')",
            name="ck_ci_outcomes_provider",
        ),
        sa.CheckConstraint(
            "provider_result IS NULL OR (provider_result <> '' AND provider_result = btrim(provider_result, E' \\t\\n\\r'))",
            name="ck_ci_outcomes_provider_result",
        ),
        sa.CheckConstraint(
            "repo = '' OR (repo = lower(repo) AND repo ~ '^[^/]+/[^/]+$')",
            name="ck_ci_outcomes_repo",
        ),
        sa.CheckConstraint(
            "result IN ('passed', 'failed', 'error', 'timed_out', 'cancelled', 'skipped', 'neutral', 'unknown')",
            name="ck_ci_outcomes_result",
        ),
        sa.CheckConstraint(
            "run_id <> '' AND run_id = btrim(run_id, E' \\t\\n\\r')",
            name="ck_ci_outcomes_run_id",
        ),
        sa.CheckConstraint(
            "run_url IS NULL OR (run_url <> '' AND run_url = btrim(run_url, E' \\t\\n\\r'))",
            name="ck_ci_outcomes_run_url",
        ),
        sa.CheckConstraint(
            "source_event_id IS NULL OR (source_event_id <> '' AND source_event_id = btrim(source_event_id, E' \\t\\n\\r'))",
            name="ck_ci_outcomes_source_event_id",
        ),
        sa.CheckConstraint(
            "source_event_type IS NULL OR (source_event_type <> '' AND source_event_type = btrim(source_event_type, E' \\t\\n\\r'))",
            name="ck_ci_outcomes_source_event_type",
        ),
        sa.CheckConstraint(
            "source_spec_version IS NULL OR (source_spec_version <> '' AND source_spec_version = btrim(source_spec_version, E' \\t\\n\\r'))",
            name="ck_ci_outcomes_source_spec_version",
        ),
        sa.CheckConstraint(
            "workflow_id IS NULL OR (workflow_id <> '' AND workflow_id = btrim(workflow_id, E' \\t\\n\\r'))",
            name="ck_ci_outcomes_workflow_id",
        ),
        sa.CheckConstraint(
            "pr_number IS NULL OR pr_number BETWEEN 1 AND 9223372036854775807",
            name="ck_ci_outcomes_pr_number",
        ),
        sa.CheckConstraint(
            "reason IS NULL OR char_length(reason) <= 4096",
            name="ck_ci_outcomes_reason",
        ),
        sa.CheckConstraint(
            "run_attempt IS NULL OR run_attempt BETWEEN 1 AND 9223372036854775807",
            name="ck_ci_outcomes_run_attempt",
        ),
        sa.CheckConstraint("schema_version = 1", name="ck_ci_outcomes_schema_version"),
        sa.PrimaryKeyConstraint("outcome_id"),
    )
    op.create_index(
        "ix_ci_org_commit", "ci_outcomes", ["org_id", "commit_sha"], unique=False
    )
    op.create_index(
        "uq_ci_run",
        "ci_outcomes",
        ["org_id", "provider", "run_id", sa.literal_column("coalesce(run_attempt, 0)")],
        unique=True,
    )
    op.create_table(
        "developer_decisions",
        sa.Column("decision_id", sa.Text(), nullable=False),
        sa.Column("org_id", sa.Text(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("agent_harness", sa.Text(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("explicit", sa.Boolean(), nullable=False),
        sa.Column("interaction_mode", sa.Text(), nullable=False),
        sa.Column("commit_sha", sa.Text(), nullable=True),
        sa.Column("call_id", sa.Text(), nullable=True),
        sa.Column("edit_retention_score", sa.Float(), nullable=True),
        sa.Column("observation_delay_ms", sa.BigInteger(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "agent_harness IN ('claude-code', 'copilot', 'codex', 'pi')",
            name="ck_decisions_agent_harness",
        ),
        sa.CheckConstraint(
            "call_id IS NULL OR (call_id <> '' AND call_id = btrim(call_id, E' \\t\\n\\r'))",
            name="ck_decisions_call_id",
        ),
        sa.CheckConstraint(
            "commit_sha IS NULL OR (commit_sha ~ '^(?:[0-9a-f]{40}|[0-9a-f]{64})$')",
            name="ck_decisions_commit_sha",
        ),
        sa.CheckConstraint(
            "decision_id <> '' AND decision_id = btrim(decision_id, E' \\t\\n\\r')",
            name="ck_decisions_decision_id",
        ),
        sa.CheckConstraint(
            "interaction_mode IN ('agent', 'inline')",
            name="ck_decisions_interaction_mode",
        ),
        sa.CheckConstraint(
            "org_id ~ '^[a-z0-9][a-z0-9._-]{0,63}$'", name="ck_decisions_org_id"
        ),
        sa.CheckConstraint(
            "session_id <> '' AND session_id = btrim(session_id, E' \\t\\n\\r')",
            name="ck_decisions_session_id",
        ),
        sa.CheckConstraint(
            "user_id IS NULL OR (user_id <> '' AND user_id = btrim(user_id, E' \\t\\n\\r'))",
            name="ck_decisions_user_id",
        ),
        sa.CheckConstraint(
            "edit_retention_score IS NULL OR edit_retention_score BETWEEN 0.0 AND 1.0",
            name="ck_decisions_edit_retention_score",
        ),
        sa.CheckConstraint(
            "observation_delay_ms IS NULL OR observation_delay_ms >= 0",
            name="ck_decisions_observation_delay_ms",
        ),
        sa.PrimaryKeyConstraint("decision_id"),
    )
    op.create_index(
        "uq_decisions_keyed",
        "developer_decisions",
        [
            "org_id",
            "agent_harness",
            "session_id",
            "accepted",
            "explicit",
            "interaction_mode",
            "occurred_at",
            "call_id",
        ],
        unique=True,
        postgresql_where=sa.text(
            "call_id IS NOT NULL AND agent_harness = 'claude-code'"
        ),
    )
    op.create_index(
        "uq_decisions_natural",
        "developer_decisions",
        [
            "org_id",
            "agent_harness",
            "session_id",
            "file_path",
            "accepted",
            "explicit",
            "interaction_mode",
            "occurred_at",
            sa.literal_column("coalesce(call_id, '')"),
            sa.literal_column("coalesce(observation_delay_ms, -1)"),
        ],
        unique=True,
        postgresql_where=sa.text("call_id IS NULL OR agent_harness != 'claude-code'"),
    )
    op.create_table(
        "edit_observations",
        sa.Column("observation_id", sa.Text(), nullable=False),
        sa.Column("org_id", sa.Text(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("agent_harness", sa.Text(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("call_id", sa.Text(), nullable=False),
        sa.Column("applied_text", sa.Text(), nullable=False),
        sa.Column("observed_file_text", sa.Text(), nullable=False),
        sa.Column("external_lines_added", sa.BigInteger(), nullable=True),
        sa.Column("external_lines_removed", sa.BigInteger(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "agent_harness IN ('claude-code', 'copilot', 'codex', 'pi')",
            name="ck_edit_observations_agent_harness",
        ),
        sa.CheckConstraint(
            "call_id <> '' AND call_id = btrim(call_id, E' \\t\\n\\r')",
            name="ck_edit_observations_call_id",
        ),
        sa.CheckConstraint(
            "observation_id <> '' AND observation_id = btrim(observation_id, E' \\t\\n\\r')",
            name="ck_edit_observations_observation_id",
        ),
        sa.CheckConstraint(
            "org_id ~ '^[a-z0-9][a-z0-9._-]{0,63}$'", name="ck_edit_observations_org_id"
        ),
        sa.CheckConstraint(
            "session_id <> '' AND session_id = btrim(session_id, E' \\t\\n\\r')",
            name="ck_edit_observations_session_id",
        ),
        sa.CheckConstraint(
            "user_id IS NULL OR (user_id <> '' AND user_id = btrim(user_id, E' \\t\\n\\r'))",
            name="ck_edit_observations_user_id",
        ),
        sa.CheckConstraint(
            "(external_lines_added IS NULL OR external_lines_added >= 0) AND (external_lines_removed IS NULL OR external_lines_removed >= 0)",
            name="ck_edit_observations_external_counts",
        ),
        sa.PrimaryKeyConstraint("observation_id"),
    )
    op.create_index(
        "uq_edit_observations_call",
        "edit_observations",
        ["org_id", "agent_harness", "session_id", "call_id"],
        unique=True,
    )
    op.create_table(
        "fact_quarantine",
        sa.Column(
            "quarantine_revision",
            sa.BigInteger(),
            sa.Identity(always=True),
            nullable=False,
        ),
        sa.Column("quarantine_id", sa.Text(), nullable=False),
        sa.Column("org_id", sa.Text(), nullable=False),
        sa.Column("fact_table", sa.Text(), nullable=False),
        sa.Column("fact_id", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "action IN ('quarantine', 'release')", name="ck_quarantine_action"
        ),
        sa.CheckConstraint(
            "btrim(reason, E' \\t\\n\\r') <> ''", name="ck_quarantine_reason"
        ),
        sa.CheckConstraint(
            "fact_id <> '' AND fact_id = btrim(fact_id, E' \\t\\n\\r')",
            name="ck_quarantine_fact_id",
        ),
        sa.CheckConstraint(
            "fact_table IN ('inference_calls', 'developer_decisions', 'ci_outcomes', 'pushes', 'edit_observations', 'rejected_edits')",
            name="ck_quarantine_table",
        ),
        sa.CheckConstraint(
            "org_id ~ '^[a-z0-9][a-z0-9._-]{0,63}$'", name="ck_quarantine_org_id"
        ),
        sa.CheckConstraint(
            "quarantine_id <> '' AND quarantine_id = btrim(quarantine_id, E' \\t\\n\\r')",
            name="ck_quarantine_quarantine_id",
        ),
        sa.PrimaryKeyConstraint("quarantine_revision"),
        sa.UniqueConstraint("quarantine_id", name="uq_quarantine_id"),
    )
    op.create_index(
        "ix_quarantine_fact",
        "fact_quarantine",
        ["org_id", "fact_table", "fact_id", "quarantine_revision"],
        unique=False,
    )
    op.create_table(
        "inference_calls",
        sa.Column("schema_version", sa.BigInteger(), nullable=False),
        sa.Column("inference_call_id", sa.Text(), nullable=False),
        sa.Column("org_id", sa.Text(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("gateway_provider", sa.Text(), nullable=False),
        sa.Column("model_provider", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("input_messages", sa.Text(), nullable=False),
        sa.Column("output_messages", sa.Text(), nullable=False),
        sa.Column("input_tokens", sa.BigInteger(), nullable=True),
        sa.Column("output_tokens", sa.BigInteger(), nullable=True),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("model_call_id", sa.Text(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "gateway_provider IN ('litellm', 'portkey', 'helicone', 'unknown')",
            name="ck_inference_calls_gateway_provider",
        ),
        sa.CheckConstraint(
            "inference_call_id <> '' AND inference_call_id = btrim(inference_call_id, E' \\t\\n\\r')",
            name="ck_inference_calls_inference_call_id",
        ),
        sa.CheckConstraint(
            "model_call_id IS NULL OR (model_call_id <> '' AND model_call_id = btrim(model_call_id, E' \\t\\n\\r'))",
            name="ck_inference_calls_model_call_id",
        ),
        sa.CheckConstraint(
            "org_id ~ '^[a-z0-9][a-z0-9._-]{0,63}$'", name="ck_inference_calls_org_id"
        ),
        sa.CheckConstraint(
            "session_id <> '' AND session_id = btrim(session_id, E' \\t\\n\\r')",
            name="ck_inference_calls_session_id",
        ),
        sa.CheckConstraint(
            "user_id IS NULL OR (user_id <> '' AND user_id = btrim(user_id, E' \\t\\n\\r'))",
            name="ck_inference_calls_user_id",
        ),
        sa.CheckConstraint(
            "(input_tokens IS NULL OR input_tokens >= 0) AND (output_tokens IS NULL OR output_tokens >= 0) AND (duration_ms IS NULL OR duration_ms >= 0)",
            name="ck_inference_calls_usage",
        ),
        sa.CheckConstraint(
            "schema_version = 1", name="ck_inference_calls_schema_version"
        ),
        sa.PrimaryKeyConstraint("inference_call_id"),
    )
    op.create_index(
        "ix_inference_calls_org_time",
        "inference_calls",
        ["org_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        "uq_inference_calls_model_call",
        "inference_calls",
        ["org_id", "gateway_provider", "model_call_id"],
        unique=True,
        postgresql_where=sa.text("model_call_id IS NOT NULL"),
    )
    op.create_table(
        "pushes",
        sa.Column("push_id", sa.Text(), nullable=False),
        sa.Column("org_id", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("repo", sa.Text(), nullable=False),
        sa.Column("clone_url", sa.Text(), nullable=False),
        sa.Column("ref", sa.Text(), nullable=False),
        sa.Column("before_sha", sa.Text(), nullable=False),
        sa.Column("after_sha", sa.Text(), nullable=False),
        sa.Column("forced", sa.Boolean(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "after_sha ~ '^(?:[0-9a-f]{40}|[0-9a-f]{64})$'", name="ck_pushes_after_sha"
        ),
        sa.CheckConstraint(
            "before_sha ~ '^(?:[0-9a-f]{40}|[0-9a-f]{64})$'",
            name="ck_pushes_before_sha",
        ),
        sa.CheckConstraint(
            "org_id ~ '^[a-z0-9][a-z0-9._-]{0,63}$'", name="ck_pushes_org_id"
        ),
        sa.CheckConstraint("provider IN ('github')", name="ck_pushes_provider"),
        sa.CheckConstraint(
            "push_id <> '' AND push_id = btrim(push_id, E' \\t\\n\\r')",
            name="ck_pushes_push_id",
        ),
        sa.CheckConstraint(
            "ref <> '' AND ref = btrim(ref, E' \\t\\n\\r')", name="ck_pushes_ref"
        ),
        sa.CheckConstraint(
            "repo = '' OR (repo = lower(repo) AND repo ~ '^[^/]+/[^/]+$')",
            name="ck_pushes_repo",
        ),
        sa.PrimaryKeyConstraint("push_id"),
    )
    op.create_index(
        "uq_pushes_natural",
        "pushes",
        ["org_id", "repo", "ref", "before_sha", "after_sha"],
        unique=True,
    )
    op.create_table(
        "rejected_edits",
        sa.Column("rejection_id", sa.Text(), nullable=False),
        sa.Column("org_id", sa.Text(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("agent_harness", sa.Text(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("call_id", sa.Text(), nullable=False),
        sa.Column("proposed", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "agent_harness IN ('claude-code', 'copilot', 'codex', 'pi')",
            name="ck_rejected_edits_agent_harness",
        ),
        sa.CheckConstraint(
            "call_id <> '' AND call_id = btrim(call_id, E' \\t\\n\\r')",
            name="ck_rejected_edits_call_id",
        ),
        sa.CheckConstraint(
            "org_id ~ '^[a-z0-9][a-z0-9._-]{0,63}$'", name="ck_rejected_edits_org_id"
        ),
        sa.CheckConstraint(
            "rejection_id <> '' AND rejection_id = btrim(rejection_id, E' \\t\\n\\r')",
            name="ck_rejected_edits_rejection_id",
        ),
        sa.CheckConstraint(
            "session_id <> '' AND session_id = btrim(session_id, E' \\t\\n\\r')",
            name="ck_rejected_edits_session_id",
        ),
        sa.CheckConstraint(
            "user_id IS NULL OR (user_id <> '' AND user_id = btrim(user_id, E' \\t\\n\\r'))",
            name="ck_rejected_edits_user_id",
        ),
        sa.PrimaryKeyConstraint("rejection_id"),
    )
    op.create_index(
        "uq_rejected_edits_call",
        "rejected_edits",
        ["org_id", "agent_harness", "session_id", "call_id"],
        unique=True,
    )
    op.create_table(
        "sessions",
        sa.Column("org_id", sa.Text(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column(
            "user_id_conflict", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("first_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "org_id ~ '^[a-z0-9][a-z0-9._-]{0,63}$'", name="ck_sessions_org_id"
        ),
        sa.CheckConstraint(
            "session_id <> '' AND session_id = btrim(session_id, E' \\t\\n\\r')",
            name="ck_sessions_session_id",
        ),
        sa.CheckConstraint(
            "user_id IS NULL OR (user_id <> '' AND user_id = btrim(user_id, E' \\t\\n\\r'))",
            name="ck_sessions_user_id",
        ),
        sa.CheckConstraint(
            "first_observed_at <= last_observed_at",
            name="ck_sessions_observation_bounds",
        ),
        sa.PrimaryKeyConstraint("org_id", "session_id", name="pk_sessions"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Sediment migrations are forward-only")
