# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate `docs/reference/cli.md` — every `sediment` command and flag.

Coder's reference model: the page is produced from the CLI itself, so a new
flag cannot ship undocumented. Nothing here is hand-authored, and CI runs
`--check` to fail on a stale page.

Parser sources follow the CLI dispatch paths:

- ``sediment_cli.cli.build_parser`` — the argparse tree (`facts`, `login`,
  `export …`, quarantine verbs, `server`).
- ``sediment_cli.attribution.build_parser`` — capture setup and repair commands,
  whose flags live only there; `cli.py` carries help stubs.
- ``sediment_cli.transcript.build_parser`` — transcript help metadata; runtime
  hook parsing stays fail-soft.
- the report modules and ``sediment_api.mirror_gc``, dispatched pre-argparse
  with argv forwarded verbatim to each module's own ``build_parser``.

Report defaults that read the environment (``--org`` from
``$SEDIMENT_ORG_ID``, storage from ``$SEDIMENT_DATABASE_URL`` /
``$SEDIMENT_MIRROR_PATH``) are resolved at parser construction, so the page
is generated with those unset — it documents the contract a reader gets on
a bare shell, not one machine's environment.

The hook-only verbs (`cursor-hook`, `mark`, `union-squash-notes`, and
`push-notes`) are omitted. Operator-facing repair and transcript commands
render their real parser metadata.
"""

from __future__ import annotations

import argparse
import importlib
import json
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = REPO_ROOT / "docs" / "reference" / "cli.md"

_PLUMBING = {
    "cursor-hook",
    "mark",
    "union-squash-notes",
    "push-notes",
}

# Help stubs in cli.py whose real parser lives elsewhere: capture setup and
# repair come from the attribution tree; transcript, reports, delivery, and
# mirror-gc own their metadata. Rendering a stub would omit its real flags.
_STUBS = {
    "install",
    "uninstall",
    "doctor",
    "stamp",
    "repair-notes",
    "transcript",
    "report",
    "mirror-gc",
    "delivery",
}

_HEADER = """# CLI reference

Commands, arguments, and options for the `sediment` command-line interface
(CLI). The [Quickstart](../quickstart.md) covers installation.
The [HTTP API reference](api.md) describes server routes;
the [Schema reference](schema.md) describes Facts and export rows.

`sediment --help` lists commands. `sediment --version` prints the installed
version. `sediment <command> --help` lists that command's options.
Hook commands that the CLI hides from help are outside this reference.

Defaults come from the parsers. `—` means that the parser supplies no value;
the description names any runtime or environment fallback.
**(required)** marks a required option. If its description names an
environment default, the option is required only when that variable is unset.

<!-- Generated by scripts/gen_cli_docs.py. Edit parser sources, then regenerate. -->
"""


def _subparsers(parser: argparse.ArgumentParser):
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    return None


def _usage(parser: argparse.ArgumentParser, path: tuple[str, ...]) -> str:
    """A usage line with the real command path, not argparse's prog."""
    formatter = argparse.HelpFormatter(prog=" ".join(("sediment", *path)))
    optionals = [a for a in parser._actions if a.option_strings]
    positionals = [a for a in parser._actions if not a.option_strings]
    usage = formatter._format_usage(
        parser.usage, optionals + positionals, parser._mutually_exclusive_groups, ""
    )
    return " ".join(usage.split())


def _rows(actions: list[argparse.Action], prog: str) -> list[tuple[str, str, str]]:
    out = []
    for action in actions:
        if action.help == argparse.SUPPRESS or isinstance(
            action, argparse._SubParsersAction
        ):
            continue
        name = ", ".join(f"`{s}`" for s in action.option_strings) or f"`{action.dest}`"
        help_text = (
            (
                argparse.HelpFormatter(prog=prog)._expand_help(action)
                if action.help
                else ""
            )
            .replace("\n", " ")
            .strip()
        )
        if action.choices and not isinstance(action.choices, dict):
            choices = ", ".join(f"`{c}`" for c in action.choices)
            help_text = f"{help_text} (choices: {choices})".strip()
        if action.required and action.option_strings:
            help_text = f"{help_text} **(required)**".strip()
        default = action.default
        if default is None or default == argparse.SUPPRESS:
            default_text = "—"
        else:
            value = default if isinstance(default, str) else json.dumps(default)
            home = str(Path.home())
            if value.startswith(home + "/"):
                value = "~" + value[len(home) :]
            default_text = f"`{value}`"
        out.append((name, default_text, help_text or "—"))
    return out


def _table(title: str, rows: list[tuple[str, str, str]]) -> list[str]:
    if not rows:
        return []
    lines = [f"{title}:", "", "| Name | Default | Description |", "|---|---|---|"]
    lines += [
        "| " + " | ".join(cell.replace("|", "&#124;") for cell in row) + " |"
        for row in rows
    ]
    lines.append("")
    return lines


def _render(parser: argparse.ArgumentParser, path: tuple[str, ...]) -> list[str]:
    """One section for ``path``, then its subcommands depth-first."""
    lines: list[str] = []
    if path:
        lines += [f"{'#' * (1 + len(path))} sediment {' '.join(path)}", ""]
        description = (parser.description or "").strip()
        if description:
            lines += [" ".join(description.split()), ""]
        lines += ["```text", _usage(parser, path), "```", ""]
        positionals = [a for a in parser._actions if not a.option_strings]
        optionals = [
            a for a in parser._actions if a.option_strings and a.dest != "help"
        ]
        prog = " ".join(("sediment", *path))
        lines += _table("Arguments", _rows(positionals, prog))
        lines += _table("Options", _rows(optionals, prog))
    action = _subparsers(parser)
    if action is not None:
        for name, child in action.choices.items():
            if name in _PLUMBING or (not path and name in _STUBS):
                continue
            lines += _render(child, (*path, name))
    return lines


def render() -> str:
    cli = importlib.import_module("sediment_cli.cli")
    attribution = importlib.import_module("sediment_cli.attribution")

    lines: list[str] = []
    lines += _render(cli.build_parser(), ())

    # install/uninstall/doctor: cli.py holds help stubs, the real flags are
    # in the attribution parser. Rendered here so the page is complete.
    attribution_tree = attribution.build_parser()
    action = _subparsers(attribution_tree)
    for name, child in action.choices.items():
        if name in _PLUMBING:
            continue
        lines += _render(child, (name,))

    # mirror-gc and the reports dispatch pre-argparse; each module owns its
    # parser, so they render from those rather than cli.py's help stubs.
    lines += _render(_module_parser("sediment_api.mirror_gc"), ("mirror-gc",))
    lines += _render(_module_parser("sediment_cli.delivery"), ("delivery",))
    lines += _render(_module_parser("sediment_cli.transcript"), ("transcript",))
    lines += [
        "## sediment report",
        "",
        "Read-only reports, forwarded to their own module. An empty "
        "result exits 0, never an error.",
        "",
        "| Report | Description |",
        "|---|---|",
    ]
    lines += [
        f"| [`{name}`](#sediment-report-{name}) | {help_text} |"
        for name, (_, help_text) in cli._REPORTS.items()
    ]
    lines.append("")
    for name, (module_path, _) in cli._REPORTS.items():
        lines += _render(_module_parser(module_path), ("report", name))
    index = _table("Global options", _rows(cli.build_parser()._actions, "sediment"))
    index += ["## Command index", ""]
    for line in lines:
        if line.startswith("#"):
            command = line.lstrip("# ")
            index.append(f"- [`{command}`](#{command.replace(' ', '-')})")
    return "\n".join([_HEADER, *index, "", *lines]).rstrip() + "\n"


def _module_parser(module_path: str) -> argparse.ArgumentParser:
    """A report / mirror-gc module's own parser.

    Environment-derived defaults are stripped for the duration: `--org`
    defaults to `$SEDIMENT_ORG_ID` and is `required` without it, so a
    generator run on a configured machine would document the opposite
    contract from one on a bare shell.
    """
    saved = {
        key: os.environ.pop(key)
        for key in (
            "SEDIMENT_ORG_ID",
            "SEDIMENT_DATABASE_URL",
            "SEDIMENT_MIRROR_PATH",
        )
        if key in os.environ
    }
    try:
        return importlib.import_module(module_path).build_parser()
    finally:
        os.environ.update(saved)


def _display(path: Path) -> str:
    """Repo-relative when it is inside the repo, absolute otherwise — the
    output path is patchable, so never assume it lives under REPO_ROOT."""
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the committed page differs from the generated one",
    )
    args = parser.parse_args(argv)
    generated = render()
    if args.check:
        current = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.exists() else ""
        if current != generated:
            print(
                f"error: {_display(OUT_PATH)} is stale — run "
                "`uv run python scripts/gen_cli_docs.py`",
                file=sys.stderr,
            )
            return 1
        print(f"{_display(OUT_PATH)} is current")
        return 0
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(generated, encoding="utf-8")
    print(f"wrote {_display(OUT_PATH)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
