# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate the consumer support matrix from the versioned profile registry."""

import argparse
from pathlib import Path

from sediment_export.compatibility import PROFILES

DESTINATION = Path(__file__).resolve().parents[1] / "docs/reference/compatibility.md"


def render() -> str:
    lines = [
        "# Consumer compatibility reference",
        "",
        "Generated by `scripts/gen_compatibility_docs.py` from",
        "`packages/export/sediment_export/compatibility.py`. Don't edit this page.",
        "",
        "A canonical schema validates Sediment's contract. A consumer profile",
        "validates the exact boundary named here. Neither proves model quality,",
        "task correctness, or hosted job acceptance. Profile versions don't replace",
        "Evidence recipe versions, canonical schema versions, or Provenance.",
        "",
        "| Profile | Objective | Version | Canonical input | Supported upstream | Support |",
        "|---|---|---|---|---|---|",
    ]
    for profile in PROFILES:
        dependencies = ", ".join(
            f"`{name}=={version}`" for name, version in profile.dependencies
        )
        upstream = dependencies or "Fireworks documentation, 2026-09-13"
        lines.append(
            f"| `{profile.id}` | {profile.objective.upper()} | {profile.profile_version} | `{profile.canonical_schema}` | {upstream} | {profile.support} |"
        )
    lines += [
        "",
        "## Validation entry points",
        "",
        "| Profile | Validation |",
        "|---|---|",
    ]
    for profile in PROFILES:
        lines.append(f"| `{profile.id}` | `{profile.validation}` |")
    lines += [
        "",
        "## Output artifacts",
        "",
        "Every populated profile publishes a private directory containing",
        "`data.jsonl`, `evidence.jsonl`, and `compatibility.json`. If splitting",
        "is enabled, populated partitions use `data.train.jsonl` and",
        "`data.eval.jsonl`, with matching evidence files. Empty partitions",
        "produce no file. An empty export creates no destination.",
        "",
        "The manifest records file hashes, profile identity, skip counts, split",
        "counts, numeric Reward counts, and exact prompt overlap. The evidence",
        "sidecar preserves canonical metadata and source hashes. It isn't trainer",
        "input. Publication refuses an existing destination and validates every",
        "row before exposing the directory. Split exports reject exact prompts",
        "shared by train and eval; semantic task overlap still needs review.",
        "",
        "`skipped` counts adapter exclusions. CLI profiles preserve",
        "`canonical_skipped` from their training projection; RLVR profiles also",
        "preserve source-bundle `fragmented` counts. These populations stay",
        "separate. Low-level callers omit unavailable source populations; an",
        "explicitly supplied empty map records zero counts.",
        "",
        "See [Export for a consumer](../exports/consumer-compatibility.md) for",
        "installation, exact commands, configuration, and consumer limitations.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Fail if the generated reference differs"
    )
    args = parser.parse_args()
    content = render()
    if args.check:
        if not DESTINATION.exists() or DESTINATION.read_text() != content:
            print(
                "Consumer compatibility reference is stale; run scripts/gen_compatibility_docs.py"
            )
            return 1
    else:
        DESTINATION.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
